biblio:
	latex multidarkroom
	bibtex multidarkroom
	@echo "DONE"
	@echo "------------------------------------------------"
	@echo "Copy the multidarkroom.bbl file content to multidarkroom.tex into the \\\begin{thebibliography} command."
	@echo "Comment out the \\\bibliography{references} command in template.tex."
	@echo "------------------------------------------------"

pdf:
	pdflatex multidarkroom

